### ISSUE TITLE
ferret-data.tar.gz missing (404) while running setup.sh

### ISSUE THREAD

**Issue by gubiq** [wustl-pctg/ProWS#1]
https://github.com/wustl-pctg/ProWS/blob/8ed164fd22981a7ecf36b67211eebe8e7e151959/setup.sh#L69 cannot be downloaded.
Could you please fix this, @robertutterback
Thanks!

**Comment by robertutterback** [comment]
They must have finally cleared out my old data. I no longer have this data.

I believe @angelee provided this data to me; maybe she can help here.

I think I set it up this way because it was a fairly large file. Maybe [git LFS](https://git-lfs.github.com/) is the right solution here.

**Comment by kyle-singer** [comment]
Hi @gubiq, sorry for the delay. Apparently I was not signed up for notifications about issues.

This issue should now be resolved in commit  e2a5b11. I have added the tar file split into 16 MB chunks. The setup.sh script has been updated to instead reassemble the tar file.

**Comment by gubiq** [comment]
Thank you for the fast fix! Please see #2 to avoid creating an intermediary file.
